src/doc/extend.md

Previous link was obsolete and pointing to WHATWG link.

Update the link to theme-color documentation

---

package.json

The old license style (`license.type` and `license.url`) is [deprecated by NPM](https://docs.npmjs.com/files/package.json#license). Using [SPDX format](https://spdx.org/licenses/MIT.html) instead

Change license format to SPDX format

---

src/css/main.css

Following the lead of Twitter Bootstrap (see: https://github.com/twbs/bootstrap/pull/19000), remove the print media query that sets a max-width of 100% to images. This code was meant to prevent images from being cut off in print, but has a side effect of causing map tiles to disappear when printing medium-to-large maps (e.g., with Google Maps).
For reference, this style was added to H5BP in https://github.com/h5bp/html5-boilerplate/commit/b2faa1fc3cff20568848c98e9a51ecda61f3bf73
Fixes #1741

Remove print img max-width: 100%. 

---

dist/css/main.css
src/css/main.css

*:first-line pseudo-selector freezes window with print preview in IE 11 (tested on Windows 7 with IE 11.0.9600.17420 and 11.0.9600.18204, Windows 8.1 with IE 11.0.9600.16663, Windows 10 with IE 11.63.10586.0)
To reproduce just open: http://demo.html5boilerplate.com/ or /dist/index.html and select Print > Print preview...

Fix print styles for Internet Explorer 11

---

CHANGELOG.md
dist/index.html
src/index.html

I think [this is a good idea](https://github.com/h5bp/html5-boilerplate/issues/1747), so here's a PR. 
To be clear, this isn't dropping support for IE 8 and 9. This is simply informing users that their older browsers are outdated. This will hopefully promote an increased rate of browser upgrades so that we can eventually drop support once usage falls below whatever threshold we've established.

Tell users that IE 8 and 9 are outdated

---

src/css/main.css

See: https://medium.com/@jessebeach/beware-smushed-off-screen-accessible-text-5952a4c2cbfe
This also relates to #1874

Add white-space: nowrap to improve accessibility with long hidden content

---

README.md
dist/index.html
gulpfile.babel.js
package.json
src/index.html

Hi my friend,
I want add a new freature - generating SRI Hash for external depedencies from CDN. 
You could read more about it on: 
https://www.srihash.org/ 
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
It should be emphasized that the official website of jQuery supports this technology:
https://github.com/jquery/codeorigin.jquery.com/issues/20
You should look at: 
http://caniuse.com/#feat=subresource-integrity
Thanks in advance

Add SRI Hash for jQuery

---

src/doc/extend.md

Replaced urban legend about referencing robots.txt file for with an actually working and suggested by all major search engines method.
See:
[Google](https://support.google.com/webmasters/answer/183668?hl=en#addsitemap)
[Bing](https://www.bing.com/webmaster/help/how-to-submit-sitemaps-82a15bd4)
[Yandex](https://yandex.com/support/webmaster/indexing-options/sitemap.xml#notify-about)
ref: https://github.com/h5bp/html5-boilerplate/issues/1895, https://github.com/LotusTM/Kotsu/issues/88

Reference sitemap.xml from robots.txt file

---

src/css/main.css

`clip` [is deprecated since 2014](https://www.w3.org/TR/css-masking-1/#clip-property). It works great but already has a more future proof version: `clip-path`.
@ryuran [suggested](https://twitter.com/ryuran78/status/778943389819604992) the `clip:path: inset(50%);` notation as it's the shorter possible to mimic our old clip.
Here's [a codepen](http://codepen.io/ffoodd/pen/gwKZyq?editors=1100#) and [a post translated by Hugo Giraudel](http://hugogiraudel.com/2016/10/13/css-hide-and-seek/).
Hope it'll help :)

Deprecated clip: add clip-path as PE

---

README.md

CONTRIBUTING.md was moved to the `.github` folder in #1948 but the links in README.md were not updated.

Fix links to CONTRIBUTING.md

---

src/css/main.css

After Autoprefixer was added a comment explaining that the vendor prefixed
`::-moz-selection` and the default `::selection` can't be combined became
obsolete. I (with the help of @roblarsen) rephrased the comment to be more
general and so that it still makes sense in the dist css file. A stackoverflow link
explains why vendor prefixed selectors can't be combined with other selectors.
Fixes #1953

Improve ::selection documentation which became confusing after c7057be

---

src/doc/html.md

Yahoo's YSlow is (sadly) no longer actively maintained. The browser extensions don't work anymore and the main repo hasn't been updated for nearly four years. I suggest to remove the http://developer.yahoo.com/yslow/ link.

Remove link to ySlow

---

dist/css/main.css
src/css/main.css

Chrome currently has a bug (when printing) that results in
::first-letter being vertically misaligned under certain (seemingly
unrelated) conditions. This PR fixes issue by removing the CSS that
causes the issue.
Thanks @patrickhlauke for the heads-up on this. (https://github.com/h5bp/html5-boilerplate/issues/1961)
For reference; the Chrome issue is logged at: https://bugs.chromium.org/p/chromium/issues/detail?id=739800
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.

Fix ::first-letter in print style causing incorrect rendering in Chrome

---

dist/doc/misc.md
src/doc/misc.md

Visual Studio, BBEdit, WebStorm and others have built-in support for
Editorconfig files so we should change ‘will need to install a plugin’
to ‘may need to install a plugin’.

Editorconfig change 'will need a plugin' to 'may need'

---

src/doc/usage.md

- Updated file tree with relevant additions, filename changes and
alphabetized
- Mention that browserconfig.xml is relevant for Edge (as well as IE11)
- Remove very old link with favicon.psd. It is deprecated and doesn't
have any of the recent iPhones app sizes.

Updates to usage.md

---

src/doc/extend.md

- HTTPS links to example.com (I know it's only an example but good to encourage always using HTTPS for everything)
- Fix Markdown issue with iOS web apps code not displaying.
- Remove section incorrectly stating that 'Screen readers currently have less-than-stellar support for HTML5'. The JavaScript polyfill is largely unnecessary and hasn't been updated for 4 years.
- Rename filename reference for apple-touch-icon to be icon.png to match what is used by H5BP
- Remove the no-longer-exists Firefox OS from list of browsers which support `theme-color`  (Firefox browser does not support theme-color at this time)
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.

Docs Update (Update extend.md)

---

src/doc/extend.md

Chrome Web Store are no longer accepting submissions for web apps (Windows, Mac or Linux) so this section is no longer needed. Users can use W3C Manifest file instead to allow for users to install their webapps.
> As of 21 November 2016, all newly published packaged or hosted apps are restricted to Chrome OS, and are not available to users on Windows, Mac or Linux. Existing apps will continue to be available on all major platforms and will continue to receive updates
REF: https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

Remove 'Chrome Web Store app section'

---

src/doc/js.md

I think this is the last thing I'm doing for 6.0. Is that really real?

Updates js.md

---

src/css/main.css

This PR solves [issue 1985: macOS - VoiceOver / Chrome announcing visually hidden text out of order](https://github.com/h5bp/html5-boilerplate/issues/1985)
By removing the negative margin, and setting it to `margin: 0;`, the issue is resolved.

Fix Bug: .visuallyhidden on macOS VO

---

dist/doc/misc.md
src/doc/misc.md

No changes to code have been made. So I am ignoring test related comments.

Add documentation for humans.txt

---

package.json

This pull request handles upgrading from babel-preset-es2015 which fixes the issue when running `npm install`.
```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
```

Upgrading to babel-preset-env

---

dist/doc/extend.md
src/doc/extend.md

This was addressed nearly 5 years ago:
https://blogs.msdn.microsoft.com/ie/2013/03/11/flash-in-windows-8/

Remove info about Flash in Metro mode IE10 (no longer applicable)

---

gulpfile.babel.js
package.json

Replace `node-sri` with `ssri`

---

.github/CONTRIBUTING.md
CHANGELOG.md
dist/doc/css.md
dist/doc/html.md
src/doc/css.md
src/doc/html.md

HTTPS links

---

README.md

Yarn is popular these days and H5BP is currently getting 2.4K downloads per month (https://yarnpkg.com/en/package/html5-boilerplate) so I think it'd be good to add this here.
I changed the list of quick start options to unnumbered as they aren't steps/instructions so bullets make more sense imho.

Add Install with Yarn option

---

dist/site.webmanifest
src/site.webmanifest

This change removes the "display": "standalone" from manifest. It is better to default to the browsers default as not all websites using manifests are PWAs intended to be run fullscreen with no navigation bar.
This fixes: #2090 - Thanks @philwareham for the heads-up on this one!

Removes "display": "standalone" from manifest

---

src/doc/html.md

I've removed link to #404html section of the page, since there is on section for 404 page and in IDE I'm getting "Cannot resolve anchor #404html" warning. I hope that it makes sense.
Thanks!

Removed link to #404html

---

dist/css/normalize.css
package.json

Upgrade Normalize.css from 8.0.0 to 8.0.1

---

dist/index.html
src/index.html

closes #2102
Per my findings, the need for it as a default was rectified with the release of iOS 9.3, where the viewport no longer shrunk to accommodate overflow, as was introduced in iOS 9.
Removal of meta data no longer necessary.

remove instances of shrink-to-fit=no

---

dist/.htaccess
package.json

https://github.com/h5bp/server-configs-apache/releases/tag/3.1.0

Bump apache-server-configs to v3.1.0

---

dist/doc/html.md
src/doc/html.md

- Update https://cdn.polyfill.io from v2 to v3
- Remove unneeded `shrink-to-fit=no` meta tag

minor docs update

---

dist/doc/html.md
dist/index.html
src/doc/html.md
src/index.html

- We now include ` ga('set','transport','beacon');` Google Analytics snippet in `index.html` for improved performance
- Docs updated mentioning why we are using `analytics.js` rather than `gtag.js`. Removed link to Mathias Bynens old blog post as it's not so relevant since the async snippet is included in the official Google Developer docs. There's a link to Philip Walton's excellent guide to advanced setup which is up-to-date.

Update Google Analytics docs and snippet

---

dist/doc/html.md
src/doc/html.md

I propose to remove this paragraph:
> The jQuery CDN version was chosen over other potential candidates
([like Google's Hosted Libraries](https://developers.google.com/speed/libraries/))
because it's fast ([comparable or faster than Google by some
measures](https://www.cdnperf.com/#jsdelivr,cdnjs,google,yandex,microsoft,jquery,bootstrapcdn/https/90))
and, (unlike Google's CDN) is available to China's hundreds of millions of internet users.
For many years we [chose](https://github.com/h5bp/html5-boilerplate/issues/1191)
the Google Hosted version over the jQuery CDN because it was available
over HTTPS (the jQuery CDN was not,) and it offered a better chance of
hitting the cache lottery owing to the popularity of the Google CDN.
The first issue is no longer valid and the second is far …

jQuery CDN docs - remove unnecessary info

---

dist/doc/html.md
src/doc/html.md

- Update to `html.md` to address the recent updates to Modernizr and jQuery.
- remove unnecessary spacing before the `<link rel="manifest" href="site.webmanifest">`

update jQuery and Modernizr (Docs)

---

dist/.htaccess
package.json

REF: https://github.com/h5bp/server-configs-apache/blob/master/CHANGELOG.md
cc @LeoColomb

update Apache Server Configs to 3.2.1

---

README.md

README badges looks good. HTML5 Boilerplate is a popular project and showing the number of NPM downloads and GitHub stars on the README is a good way to show this off.

Add License, NPM Download counter and GitHub Stars counter badges

---

dist/doc/css.md
src/doc/css.md

This fixes the broken links in the CSS docs.
Thanks for spotting this @PeteSchuster  !

fix broken links in TOC

---

package.json

previous versions are end-of-life.
REF: https://github.com/nodejs/Release

bump lowest supported version of node to 8.x

---

.gitignore

Removed package-lock.json from .gitignore
package-lock.json is intended to be checked into source control, without a package-lock.json using npm makes little sense over yarn. 
I see this was added in 2017, when there was an issue with the package-lock.json updating, this issue is now long resolved.
- [X ] My code follows the code style of this project.
Thanks!

Removed package-lock.json from .gitignore

---

.travis.yml
gulpfile.babel.js
package-lock.json
package.json

Hi I saw your tweet and the issue #2150. I did the migration to Gulp 4. You can test by yourself to check if it's the intended behaviour. It should I did not change that much.
What I did exactly:
- Updated some dev dependencies used in gulp
- Changed the babel node modules to be compatible with Gulp V4
- Updated the babel config inside the package.json
- Moved Autoprefixer browserlist config from gulpfile to the package.json
My node version: v10.15.4 and npm: 6.9.0. I don't know if the projects now works for "node": ">=8" and "npm": ">=3". Maybe we need to update the engine config aswell.
Cheers ! 🍻

upgrade to gulp 4 and update others dev dependencies

---

.editorconfig

This removes the unnecessary:
```
[{.travis.yml,package.json}]
indent_size = 2
indent_style = space
```
The preceding rules state indent size of 2 and spaces anyway. (plus that linked GitHub issue regarding `package.json` has been fixed as of npm 5)

remove redundant rules from .editorconfig

---

dist/css/main.css
package-lock.json
package.json

All tests run and pass.
Note: the build removes `-webkit-box-shadow: none !important;` from the compiled CSS. I don't think that should have been there before. The webkit prefixed version hasn't been needed for a looooooong time. https://caniuse.com/#feat=mdn-css_properties_box-shadow

update dev deps

---

dist/doc/css.md
dist/doc/misc.md
src/doc/css.md
src/doc/misc.md

- There were 3x links to Normalize.css in close proximity when I think one is enough. There is a prominent link to the blog post from the Normalize homepage anyway.
- HTTPS link to www.robotstxt.org
- Remove some unneeded trailing white-spaces

HTTPS link to www.robotstxt.org and remove repeat links to normalize.css

---

dist/404.html
dist/doc/css.md
dist/doc/extend.md
dist/doc/html.md
dist/doc/js.md
dist/doc/misc.md
src/404.html
src/doc/css.md
src/doc/extend.md
src/doc/html.md
src/doc/js.md
src/doc/misc.md

- The 'Getting Started' section header no longer exists on that jQuery plugins page so I removed.
- cdn.polyfill.io is now just polyfill.io
- update Apple docs URL to prevent a redirect
- Remove CSS Tricks link to IE-only stylesheets as it only applied to IE9 and below which is no longer supported by H5BP or Microsoft
- Microsoft own docs have a rule to not include the country code so that a user gets the docs in their own locale. so a user in UK would go to https://docs.microsoft.com/en-gb/ and a US user would go to https://docs.microsoft.com/en-us/ etc. I suggest we follow their recommendation here.

Update links in docs

---

dist/doc/extend.md
dist/doc/html.md
dist/index.html
package-lock.json
src/doc/extend.md
src/doc/html.md
src/index.html

Sets anonymizeIp to true in GA snippet

---

README.md
dist/doc/TOC.md
dist/doc/css.md
dist/doc/extend.md
dist/doc/faq.md
dist/doc/html.md
dist/doc/js.md
dist/doc/misc.md
dist/doc/usage.md
src/doc/TOC.md
src/doc/css.md
src/doc/extend.md
src/doc/faq.md
src/doc/html.md
src/doc/js.md
src/doc/misc.md
src/doc/usage.md

updating some markdown formatting

---

dist/doc/extend.md
dist/doc/html.md
dist/doc/misc.md
src/doc/extend.md
src/doc/html.md
src/doc/misc.md

- Fix many site redirects
- Fix a few minor grammatical issues
- Remove jQuery CDN section (no longer needed)
- Update jQuery code snippet to use latest version (3.5.1) and reword sentence to give context on what it does.
- Remove paragraph on 'Disable implicit prefetching'. This is not widely supported, recommended against and very rarely useful. I don't think its needed here.

Update docs for v8

---

dist/doc/extend.md
src/doc/extend.md

This was only needed for IE10 on Windows Phone and is no longer needed or supported.
REF: https://blogs.windows.com/windowsdeveloper/2012/11/15/adapting-your-webkit-optimized-site-for-internet-explorer-10/#step5

Remove msapplication tap highlight

---

dist/doc/html.md
dist/doc/misc.md
dist/index.html
src/doc/html.md
src/doc/misc.md
src/index.html

- Removed unneeded self-closing tags from Open Graph meta tags - we don't use them elsewhere
- Add spacing for transport-beacon in Google Analytics for consistency
- remove unneeded whitespace from `misc.md`

Consistent code formatting fix

---

README.md

https://github.com/h5bp/html5-boilerplate/pull/2273#issuecomment-675559777
I didn't find a way to link to the latest details. So I propose here: https://github.com/h5bp/html5-boilerplate/actions?query=workflow%3A%22Build+status%22+branch%3Amaster

docs: add link to CI status badge

---

dist/doc/extend.md
src/doc/extend.md

Fixes #2549
Also removes old link about IE9 dns-prefetching (page last updated 10 years ago) and updates Smart App Banner URL to prevent redirect.

remove 'Common Prefetch Links' from extend docs

---

src/doc/extend.md
src/doc/misc.md

Very minor fix to make Table of Contents match the file content after this change: https://github.com/h5bp/html5-boilerplate/commit/be09d9853161d63688f6cf78e28dfe23a383612c
I don't see a CONTRIBUTING document...am i missing that somewhere?

Move humans.txt ToC link from misc to extend doc

---

.github/workflows/build-dist.yaml
.github/workflows/publish.yaml
.github/workflows/test.yaml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

Set permissions for GitHub actions

---

.github/workflows/push-to-template.yaml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

README.md
package.json

Removing `"browserslist": [
"> 0.5%",
"last 2 versions",
"Firefox ESR",
"not dead",
"not IE 11"
],` from `package.json` will default to `defaults` (which as it happens, is exactly the same as what we have now anyway because not IE 11 is no longer needed as it's excluded anyway)

Update Browserslist config

---

.github/CONTRIBUTING.md
.github/SUPPORT.md
dist/index.html
docs/css.md
docs/usage.md
package.json
src/index.html

Remove normalize.css link. Closes #3033 
Optimize header tag order:
> How you order elements in the <head> can have an effect on the (perceived) performance of the page.
> This script helps you identify which elements are out of order.
https://github.com/rviscomi/capo.js
Thanks!

Remove normalize.css and Optimize head tag order.

---

docs/extend.md
docs/html.md

- Remove link to validator (no longer works)
- name change to X
- Update Google's structured-data/testing-tool link to prevent redirect

Update Twitter Cards docs

---

dist/index.html
docs/extend.md
docs/html.md
src/index.html

This ensures that the image added via OpenGraph `<meta>` tag has a proper alt text for use with screen readers or image-less user agents. Leaving the alt text empty is a sane fallback for when the image is purely decorative too.
Documentation and tests are irrelevant for such a change, right?

Add `og:image:alt` for accessibility.

---

.github/workflows/publish.yml
.github/workflows/push-to-template.yml
.github/workflows/test.yml

`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

ci: Use GITHUB_OUTPUT envvar instead of set-output command

---

dist/css/style.css
dist/package.json
gulpfile.mjs

Updates for gulp 5

---

.gitattributes
.github/workflows/codeql-analysis.yml
.github/workflows/publish.yml
.github/workflows/test-windows.yml
.github/workflows/test.yml
CHANGELOG.md
docs/about-this-repo.md
gulpfile.mjs

- Allow CodeQL workflow to be run from GitHub Actions WebUI at any time
- Set CodeQL to also check for best practises/code problems (as well as security)
- Capitalize Publish GH Action
- Change Windows Test workflow for consistent file extension (also means its formatted with Prettier) and remove leading empty linebreak and change title to seperate it from Ubuntu one
- Run Prettier (maybe we should add this to build script to ensure all code is formatted?)
- Change `.gitattributes` to have LF line-endings for more file types

GitHub Actions Tidy-up

---

CHANGELOG.md
dist/robots.txt
docs/misc.md
src/robots.txt

- Fix release date year for recent release on CHANGELOG
- Add https:// to www.robotstxt.org link-  this has advantage of allowing users to Ctrl+click to view site to view more details
- Remove broken `#server-configuration` in-page link (doesn't exist)

Minor docs fixes

---

dist/index.html
docs/extend.md
docs/html.md
src/index.html

Currently a `no-js` class is added to the `<html>` element, which is immediately replaced with a `js` class to allow targeting styles to whether JavaScript is or isn't enabled. This works well however has a few drawbacks:
1. It is mostly incompatible with server-side-rendered frameworks. For example, using a React-based SSR framework causes warnings due to a props mismatch on hydration, so the only safe way to perform the class swapping would be waiting until hydration has completed leading to FOUT.
2. Requires coordination of HTML and CSS so could not reliably be part of e.g. a CSS-only library or a WordPress plugin without control of the site's theme.
3. Requires managing an inline script which on its own is additional complexity and also complicates configuring a JavaScript content …

Remove JS-conditional classes

---

.github/workflows/codeql-analysis.yml
.github/workflows/dependency-review.yml
.github/workflows/publish.yml
.github/workflows/push-to-template.yml
.github/workflows/spellcheck.yml
.github/workflows/test.yml

Updated workflow files to use specific commit SHAs for actions/checkout, actions/setup-node, github/codeql-action, and streetsidesoftware/cspell-action.
This improves security and reproducibility by preventing unexpected changes from upstream action updates.
Also set 'persist-credentials: false' for checkout steps to enhance security.
REF: `https://github.com/actions/checkout/issues/485`

Pin GitHub Actions to specific commit SHAs

---

.github/workflows/dependency-review.yml
.github/workflows/ossf-scorecard.yml
.github/workflows/publish.yml
.github/workflows/push-to-template.yml
.github/workflows/test.yml

This pull request focuses on improving the security and reliability of the project's GitHub Actions workflows. The main changes include pinning GitHub Actions to specific commit SHAs for better supply chain security and introducing a new workflow to run OSSF Scorecard analysis on the repository.
**Security and reliability improvements:**
* All GitHub Actions in existing workflows (`dependency-review.yml`, `publish.yml`, `push-to-template.yml`, `test.yml`) are now pinned to specific commit SHAs instead of floating version tags, reducing the risk of supply chain attacks. [[1]](diffhunk://#diff-7cdd3ccec44c8ba176bdc3b9ef54c3f56aa210a1a4e2bb5f79d87b1e50314a18L17-R17) [[2]](diffhunk://#diff-551d1fcf87f78cc3bc18a7b332a4dc5d8773a512062df881c5aba28a6f5c48d7L30-R30) …

Add OSSF Scorecard security workflow
