h5bp/html5-boilerplate

gulpfile.babel.js
test/file_content.js

Fix license banner in main.css after #1814.

---

src/css/main.css

Adding pre-wrap to pre and blockquote for print media query as per @akhyarrh issue.

Fixes #1742

---

src/.gitattributes

Based from a collection of useful .gitattributes templates of @alexkaratarakis
https://github.com/alexkaratarakis/gitattributes

Update .gitattributes for Web Projects

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Adds Issue Template
Adds PR Template
Rewrites Contributing.md and moves it to ./github

Adds .github folder and contents Fixes #1943

---

dist/index.html
src/index.html

Changes the Link to browserhappy.com to https instead of http.
Thats it :)
Cheers Maik

refactor(html): update browsehappy to https instead of http

---

src/doc/extend.md

HTTPS some third-party links

---

src/doc/html.md

- Update Polyfill CDN to v2 which is the default version (Ref: https://cdn.polyfill.io )
- Switch the JQuery from Google's CDN to Jquery's CDN to match the main index.html
- Update to jQuery 3.2.1.
- Add SRI hash to jQuery link

Update polyfill JS example

---

gulpfile.babel.js

was previously IE 8 and above
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] All new and existing tests passed.

Update autoprefixer to IE 9 and above

---

src/doc/html.md

Fix typos and markdown errors

---

README.md

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.

Remove link to the retired initializr site

---

src/doc/usage.md

Updating usage.md

---

src/doc/faq.md

This PR updates the faq. It probably needs to be expanded, but it's no longer referencing old stuff.

Updating faq.md

---

dist/.gitattributes
dist/doc/TOC.md
dist/doc/css.md
dist/doc/extend.md
dist/doc/faq.md
dist/doc/html.md
dist/doc/js.md
dist/doc/usage.md
package.json

Docs updated.... So much 6.0-ness.

Docs updated

---

src/css/main.css

This change fixes bugs found in #1985

1985 - fix VoiceOver reading order bug with visually hidden text

---

CHANGELOG.md
dist/css/main.css
src/css/main.css

Last visible task for 6.0 (still need to clean up the npm package)

updates changelog and dist css

---

package.json

Updates package.json for npm

---

CHANGELOG.md
dist/css/main.css
package.json
src/css/main.css

Restores stable visuallyhidden

---

gulpfile.babel.js

Fixed JSHint errors

---

src/index.html

https://stackoverflow.com/questions/33767533/what-does-the-shrink-to-fit-viewport-meta-attribute-do
It worth?
I am trying to help please don't blame me

What about the meta tag, shrink-to-fit=no

---

dist/doc/usage.md

Please the word 'be' duplicated and corrected that. 
Thanks.
- [ x] I have updated the documentation accordingly.

double word on line 21 (be)

---

dist/css/main.css
src/css/main.css

HTTPS link to printing CSS documentation
Removed dead link to http://www.sanbeiji.com/archives/953

Minor CSS comments update

---

dist/doc/extend.md
src/doc/extend.md

Updated link to RSS Atom information to point to Wikipedia as previous link is dead.
Fixes #2023 - reported by @stardisblue (thanks!)

update link to Atom RSS

---

src/css/main.css

Remove `clip-path`

---

dist/doc/html.md
src/doc/html.md

plus correct capitalization of JavaScript

Update JS head snippets (jQuery and modernizr versions)

---

dist/.gitattributes
src/.gitattributes

[Babel](https://babeljs.io/) and [Prettier](https://prettier.io/) are the most used front-end tools nowadays.

Add .babelrc and .prettierrc to .gitattributes

---

package.json

Update gulp-jshint 

---

CHANGELOG.md
dist/css/main.css
dist/index.html
package-lock.json
package.json
src/index.html

- Update `CHANGELOG.md` date
- Update dev deps
- Indenting on `index.html` to 2 space (was 4 space)
- Update version number to 6.1.0

Prepare 6.1.0 release

---

src/doc/extend.md

"value" is not a valid attribute on element meta (http://w3c.github.io/html/single-page.html#the-meta-element).
According to https://support.google.com/webmasters/answer/79812?hl=en,
content="notranslate" is recommended to use.
Thanks!

change the attribute of "notranslate" to "content"

---

dist/doc/extend.md
src/doc/extend.md

- Removed dead link to http://dayofjs.com/videos/22158462/web-browsers_alex-russel
- Fix many redirects to browser docs on Mozilla, Apple, Faceook and Microsoft sites

Fixing links on the EXTEND page

---

package.json

bump eslint version to 5.6.0

---

test/file_content.js
test/file_existence.js

Removes out of date comments

---

.travis.yml
package.json

This removes the dependency and doesn't restore the functionality. It's terrible, but this has been hanging open for a while now so ¯\_(ツ)_/¯ 
closes #2020

removing travis-after-all

---

src/doc/css.md

Also, no need to dupe this documentation over two repos.

Updating CSS docs to reference main.css

---

dist/doc/css.md
dist/doc/html.md

This updates the markdown files in the `dist` dir.

the CSS and html MD files hadn't been updated

---

dist/css/main.css

The latest update from `main.css` wasn't included in the dist dir.

update CSS from main.css in dist

---

dist/index.html
src/index.html

This removes 'defer' from the Google Analytics script.
- It was only included in H5BP as it added non-blocking support for older browsers, but as H5BP doesn't support IE8/IE9 anymore this is no longer needed. (REF: https://github.com/h5bp/html5-boilerplate/pull/1696#issue-33685112)
- It has no benefit if ran at the bottom of the page anyway (REF: https://github.com/h5bp/lazyweb-requests/issues/42#issuecomment-1779556)
- It changes the execution time of the analytics.js script on **_all_** browsers and could negatively impact analytics tracking. (REF: https://github.com/h5bp/html5-boilerplate/pull/1696#issuecomment-96118051 )
- The official Google Analytics snippet doesn't use/advise 'defer' in their async snippet (REF: https://developers.google.com/analytics/devguides/collection/analyticsj …

Remove 'defer' from Google Analytics snippet

---

CHANGELOG.md

Work-in-progress CHANGELOG update.

v7.2.0 release

---

package.json

Update version number in `package.json`

update version number to v7.2.0

---

dist/css/main.css
package.json

...and fix a security vuln in `gulp-load-plugins`:
REF: https://github.com/jackfranklin/gulp-load-plugins#changelog

update version number in main.css by making a new build

---

CHANGELOG.md

add PRs 2134, 2137 and 2138 to the Docs update section in `CHANGELOG.md`

Add docs update PRs to CHANGELOG

---

dist/browserconfig.xml
src/browserconfig.xml

To match .`editorconfig` styleguide and also reduces file-size from 417 bytes to 381. :-)

browserconfig.xml: change indent size to 2

---

dist/doc/extend.md
src/doc/extend.md

HTTPS link to https://ogp.me/

---

package.json

Rearranged `package.json` a bit so the name and version is at the top- I think this makes more logical sense.
Added bugs and keywords which could be useful for users. Please do review the keywords added - maybe there are some other potentially useful ones?
REF:
- https://docs.npmjs.com/files/package.json#keywords
- https://docs.npmjs.com/files/package.json#bugs

Add bugs URL and keywords array to `package.json`

---

dist/doc/js.md
src/doc/js.md

prevents a redirect... and remove an unneeded trailing space

remove www from modernizr.com link

---

dist/doc/misc.md
src/doc/misc.md

The h5bp/server-configs-apache wiki is no longer online
Thanks!

update links to enable-apache-httpd-modules

---

.eslintrc.js
dist/404.html
src/404.html

Change indenting to 2 spaces to match `.editorconfig` code guide

---

src/doc/faq.md

- [ x] Bug fix (non-breaking change which fixes an issue)
Over a year ago, the answer to one of the questions was removed for v7.0 but the question itself was not removed.

Remove Question with No Answer

---

.travis.yml

REF: https://nodejs.org/en/about/releases/
Thanks!

Remove Node 8 (no longer supported)

---

dist/doc/html.md
dist/index.html
src/doc/html.md
src/index.html

This commit removes the Browser Upgrade Prompt code we've had for oh so many years.
fixes #2210

Removing Browser Upgrade Prompt

---

dist/css/main.css
gulpfile.babel.js
package-lock.json
package.json

Adds main.css 2.1.0

---

dist/doc/html.md
dist/index.html
src/doc/html.md
src/index.html

todo: add docs and maybe a comment?
I think this is okay. Even if there's a negative aspect to having empty values, we ship other stuff that doesn't make sense to leave blank (the lang attribute) or to ship unedited (the GA snippet.) This will be good to include and document. 
closes #2211

adds open graph metadata

---

dist/.gitignore
dist/doc/extend.md
dist/doc/html.md
dist/doc/misc.md
dist/package-lock.json
dist/package.json
gulpfile.babel.js
src/.gitignore
src/doc/extend.md
src/doc/html.md
src/doc/misc.md
src/package-lock.json
src/package.json
test/file_existence.js

This is a tracking branch for v8 integrations. A few of the changes we'll be making for this are big enough that I want a clean place to be able to stage them before merging them into master.

Release V8.0.0

---

README.md

Docs: Fix typo in README.md

---

dist/doc/extend.md
src/doc/extend.md

updates extend.md

---

src/doc/html.md

Originally offered to write more, but I realized that would constitute legal advice that I have no business giving and doesn't belong in software documentation anyway. Instead just put a simple warning and a link to relevant Google documentation.  
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
Thanks!

docs: Add warning about Google Analytics and GDPR

---

dist/doc/misc.md
dist/package.json
src/doc/misc.md
src/package.json

Sorted with https://github.com/cameronhunter/prettier-package-json and relevant minor docs update

Formatting improvements for package.json

---

dist/doc/html.md
src/doc/html.md

Adjust jQuery install command

---

.github/dependabot.yml

change update frequency to cut down on PR 'noise'.
REF: https://dependabot.com/docs/config-file/#available-schedules

Change update check in dependabot config to weekly

---

dist/doc/html.md
src/doc/html.md

Fix incorrect open graph documentation

---

.github/workflows/test.yaml

Update nodejs version and action

---

dist/doc/html.md
src/doc/html.md

Remove the hard line break in the middle of a link title (about viewport meta tag) as some markdown parsers don't account for that (and ones that do seem to maintain the line break which isn't necessarily desired).
Tidy up all links so no hard line break appears in the link markdown (perhaps some overly excited line formatting tool was used).
See https://youtrack.jetbrains.com/issue/IDEA-263568
Thanks!

Update html.md to tidy up link markdown

---

dist/.htaccess
dist/package-lock.json
package-lock.json
package.json

Note: I noticed that the build process didn't run at first on my Windows PC with a 'Error: [BABEL]: Cannot find module '@babel/helper-define-map' error. I deleted node_modules and rebuilt and it worked fine. Just thought I'd mention that.

Update dev deps and rebuild

---

README.md

Fix URL typo in README.md

---

dist/doc/html.md
dist/package-lock.json
src/doc/html.md

This PR also updates dist/package-lock.json

update jQuery to 3.6.0

---

dist/doc/html.md

docs: update mdn link

---

dist/.htaccess
dist/package-lock.json
src/doc/html.md

Some PRs had been merged without a build being run to update the `/dist` directory. This PR fixes that.

Run build update

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/workflows/test.yaml
README.md
dist/doc/css.md
dist/doc/html.md
src/doc/css.md
src/doc/html.md

closes #2583 
We'll pull this in and then immediately change the main branch name so stuff doesn't break.

replaces references to master with main

---

.github/PULL_REQUEST_TEMPLATE.md

Add link to CONTRIBUTING file

---

README.md

Remove broken DevDependency status badge from README

---

package-lock.json
package.json

upgrades eslint closes #2624

---

README.md

None of the above. I updated the README to accuratel reflect the browsers we support based on `package.json`.
Thanks!

Update README.md to point to browserslist in package.json

---

.github/workflows/push-to-template.yaml

Just picking up the work @vltansky was doing since I have some time right now. I've created the template repo, so it's just a matter of making sure this works and it a tidy user experience. The fundamentals are there, I think.

Push releases to Template Repo

---

README.md

Browserlist part 2

---

.gitignore

This solves #2653, which is a simple quality of life feature for Mac users. Not much to say here other than that.

Adds .DS_Store file to .gitignore and solves #2653

---

README.md

"About this repo" documentation

---

README.md

Update "Browser support" section in README

---

.cspell.json
.github/workflows/spellcheck.yml

This is setup to display typos in a PR review UI and will warn (but not error) if any detected.
Thanks!

Add Spellcheck GitHub Action

---

docs/about-this-repo.md

I'm going to publish this document as a blog post, BTW. Anyone interested can basically watch my editorial process in chunks.
Closes #2764 
Thanks!

About this repo documentation

---

.cspell.json

I'll try to catch them all with this PR

Update .cspell.json with more false positives

---

README.md
docs/extend.md
docs/faq.md
docs/js.md
docs/misc.md

Minor grammar and terminology fixes (found via https://textlint.github.io/)

Minor grammar and terminology fixes

---

src/package.json

- [] I have added tests to cover my changes.
Thanks!

sets package to private by default (closes #2887)

---

dist/package.json

I awaken from my new job (and prior job loss) shaped slumber!

updating dist with latest

---

docs/extend.md
docs/usage.md
package-lock.json
package.json

Removing humans.txt reference

---

src/package.json

Added a period for grammatical correctness in the documentation

---

dist/.editorconfig
src/.editorconfig

Added line feed
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
- [x ] I have read the **[CONTRIBUTING](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)** document.
Thanks!

Add 'end_of_line = lf' to .editorconfig

---

README.md

Update download URL to v9.
Thanks!

Update README.md's download URL

---

CHANGELOG.md

Appears not applicable, as this is a documentation change, not a code change?
Thanks!

Correct year in CHANGELOG.md

---

CHANGELOG.md
README.md

The change involves correction in the following:
a closing parenthesis was omitted in changelog.md file and a misspelling was made in Readme.md file.
Thanks!

Fix typo in README.md and CHANGELOG.md files

---

CHANGELOG.md
dist/css/style.css
package-lock.json
package.json

Cleaning up three bits and bobs. I'm going to update the Changelog now.

Release 9.0.1

---

.github/ISSUE_TEMPLATE/config.yml

Intended to help cut down on empty/blank/test issue submissions.
REF: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

Update Issue Config

---

.vscode/extensions.json
.vscode/settings.json

This pull request introduces development environment improvements by adding recommended VS Code extensions and configuring editor settings for consistent formatting and linting.
* [`.vscode/extensions.json`](diffhunk://#diff-c16655a98a3ee89a7636a59c59a72b0e93649e3a1e947327cfc43a1336b4e912R1-R8): Added recommendations for VS Code extensions, including ESLint, EditorConfig, Prettier, and a spell checker, to standardize the development environment.
* [`.vscode/settings.json`](diffhunk://#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357R1-R15): Configured VS Code settings to use Prettier as the default formatter for multiple file types, enable format-on-save, apply ESLint fixes on save for JavaScript and TypeScript, validate files with ESLint, render all whitespace, and …

Add .vscode/settings.json & extensions.json files to project
